### ISSUE TITLE
Description of the different variables?

### ISSUE THREAD

**Issue by lyttol** [zeobviouslyfakeacc/WildlifeBegone#1]
Sorry, not sure how to message you so I thought this might work... Can you explain what these do and how they interact with each other? Save me a bit of messing around. Sorry if its linked somewhere, I did try a google search!

"SpawnRegionActiveTimeMultiplier": 0.1, (is this the chance that a particular spawn region is active in a game?)
"MaximumRespawnsPerDayMultiplier": 0.1, (?No more than one respawn of an active spawn region every 10 days? per spawn location?)

(restored for context -zeobviouslyfakeacc)

**Comment by lyttol** [comment]
oh and these! "RerollActiveSpawnersTimeMultiplier": 2.0,
		"ActiveSpawnerCountMultiplier 0.4

**Comment by zeobviouslyfakeacc** [comment]
Heyo!

Yeah, I don't think I've documented these values anywhere :/

WildlifeBegone is one of those mods that I've always wanted to re-make with a pretty settings GUI and a real readme, but I just never got around to it. And now that Hinterland could release an update that'll remove / severely restrict our ability to make mods in the next couple of weeks, I just can't see myself putting a lot of time into modding anymore.

Anyway.

So in the game, there are lots of spawn regions, which you can basically imagine as circles drawn on the game map, within which animals will spawn and wander around in. These spawn regions have different properties, like: what animals they spawn, the center and the radius of that imaginary circle on the map, and so on. The ones that WildlifeBegone focuses on are the following:

- `m_ChanceActive`: Spawn regions are not always active, so animals don't always roam there. In most cases, spawn regions re-roll whether they should be active every 24 (in-game) hours, and the probability that they'll be active for the next 24 hours is `m_ChanceActive` percent.
- `m_MaxRespawnsPerDay[Pilgrim|Voyageur|Stalker|Interloper]`: Once an animal dies / falls out of the world / is trapped (rabbit), the game will set a timer that will elapse in `1 / m_MaxRespawnsPerDayX` days. Once the timer elapses, an animal will respawn. Note that there is only one respawn timer per spawn region: if you kill another animal just before the timer elapses, the timer will reset and you'll have to wait the full X days for a respawn again.
- `m_MaxSimultaneousSpawns[Day|Night][Pilgrim|Voyageur|Stalker|Interloper]`: Determines the maximum number of animals that each spawn region can contain. There are separate values for day and night, and no animals can spawn during a blizzard.

These properties correspond 1-to-1 to the following values in the config file:

- `SpawnRegionActiveTimeMultiplier` just changes the `m_ChanceActive` value: `new(m_ChanceActive) = original(m_ChanceActive) * SpawnRegionActiveTimeMultiplier`.  
  This is the easiest way to influence the number of animals you'll encounter. The lower `SpawnRegionActiveTimeMultiplier` is, the lower `m_ChanceActive` will be, and thus the smaller the number of active spawn regions will be at any time, leading to fewer animals roaming the game world.  
  However, as each spawn region can contain multiple animals, reducing this value by a large amount without also changing the other variables can lead to "clumping": The parts of the map that don't contain any active spawn regions will be completely barren of life, but there will still be areas with 4-5 wolves at the same time.
  Increasing this value will increase the number of animals you'll encounter, but only to a certain extent. Once the multiplier is high enough that all spawn regions are always active, increasing the multiplier further won't have any effect.
- `MaximumRespawnsPerDayMultiplier` changes how long it will take animals to respawn: `new(m_MaxRespawnsPerDayX) = original(m_MaxRespawnsPerDayX) * MaximumRespawnsPerDayMultiplier`. The smaller this value, the longer it will take animals to respawn.
  If you set this variable to 0, animals will never be allowed to respawn - they'll become a finite resource.
- `MaximumSpawnedAnimalsMultiplier` changes the `m_MaxSimultaneousSpawnsXY` variables in the following way:  
  `new(m_MaxSimultaneousSpawnsXY) = max(1, round(original(m_MaxSimultaneousSpawnsXY) * MaximumSpawnedAnimalsMultiplier))`.  
  So in general, the lower this value, the fewer animals each spawn region will contain; and the higher this value, the more animals per region. If you want to have *a lot* more animals in the game, this is this is the main variable you should increase.  
  
  Here is a table of how different values of `MaximumSpawnedAnimalsMultiplier` will affect the `m_MaxSimultaneousSpawnsXY` values of each spawn region:
  
  multiplier v / orig max > | 1 | 2 | 3 | 4 | 5
  :--: | -- | -- | -- | -- | --
  **1.0** | 1 | 2 | 3 | 4 | 5
  **0.9** | 1 | 2 | 3 | 4 | 5
  **0.8** | 1 | 2 | 2 | 3 | 4
  **0.7** | 1 | 1 | 2 | 3 | 4
  **0.6** | 1 | 1 | 2 | 2 | 3
  **0.5** | 1 | 1 | 2 | 2 | 3
  **0.4** | 1 | 1 | 1 | 2 | 2
  **0.3** | 1 | 1 | 1 | 1 | 2
  **0.2** | 1 | 1 | 1 | 1 | 1
  **0.1** | 1 | 1 | 1 | 1 | 1
  **0.0** | 1 | 1 | 1 | 1 | 1

That's it for 99 % of spawn regions.

However, some spawn regions don't use the `m_ChanceActive` variable to determine whether they should be active or not. Instead, some spawn regions are bundled together into a spawner group. (I think these only exist in ML, PV, and CH.) The spawner group will select one or multiple of its spawn regions to be active, ignoring the `m_ChanceActive` altogether.

To also take care of these spawner groups, there's the `ActiveSpawnerCountMultiplier` and `RerollActiveSpawnersTimeMultiplier` variables. As these spawner groups are so rare, there's no distinction on the type of animal they spawn.

- `ActiveSpawnerCountMultiplier` reduces the number of spawn regions that each spawner group will set to active. It uses the same formula as `MaximumSpawnedAnimalsMultiplier`, so consult the table there. The smaller this value, the fewer spawn regions will be active; the higher this value, the more spawn regions will be active.
- `RerollActiveSpawnersTimeMultiplier` modifies how often the spawner group changes which spawn groups should be active. Increasing this value makes it so the same spawn regions stay active for longer. Decreasing this value causes the active spawn regions to change more often.
If you set this value to 0.0, the same set of spawn regions will always stay active.

---

If you set all config variables to 1.0, the game should behave as if WildlifeBegone isn't even installed.
Setting values to 0.0 is a bit of an edge case, but it should usually be okay.
If you set either of the config variables to a negative value, you'll probably summon Cthulhu, so don't do that.
